<a href="https://colab.research.google.com/github/JF11579/A-Year-s-Worth-of-Google-Searches/blob/master/Condo_Analyses_DropDown.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Overview

### The goal of this file is to be able to drop in MLS data and quickly get a scatter plot where the points reflect the Condition/Appearance and that let's one filter for Bedroom and Bath count.

# Libraries

In [1]:
import pandas as pd
from google.colab import drive
import plotly.express as px
import numpy as np
import plotly.graph_objs as go
import plotly.io as pio

# Options

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Data

In [3]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Change to the directory containing your CSV
%cd /content/drive/MyDrive/DATA/Real_Estate_Data

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/DATA/Real_Estate_Data

In [4]:

condo = pd.read_csv('Annonymous_Condo_data_Nov_23.csv')
condo.head(3)

,Exp_Date,Appearance,Days_On_Market,Listing_Date,Listing_Price,ML#,REO,Sold_Price,Style,Unit_on_Floor_#,Development,Bath,Bedrooms,Contract_Date,count,Year,Month_Year,Month
0,1/15/2023,Mint,9,7/05/2022,188000,2286,N,205000,Garden Apartment,1,Lisaberg,1.0,1,2022-07-22,11.0,2022.0,07-2022,7
1,1/07/2023,Description Missing,34,7/07/2022,179999,435,N,172000,Garden Apartment,1,East Melissa,1.0,2,2022-08-10,70.0,2022.0,08-2022,8
2,1/05/2023,Description Missing,18,7/07/2022,149999,5535,N,150000,Garden Apartment,2,East Melissa,1.0,1,2022-07-25,70.0,2022.0,07-2022,7

In [5]:
condo.tail(20)

,Exp_Date,Appearance,Days_On_Market,Listing_Date,Listing_Price,ML#,REO,Sold_Price,Style,Unit_on_Floor_#,Development,Bath,Bedrooms,Contract_Date,count,Year,Month_Year,Month
938,10/28/2022,Mint,13,4/28/2022,205000,2825,N,220000,Garden Apartment,2.0,Port Regina,1.0,1,2022-05-11,10.0,2022.0,05-2022,5
939,07/03/2023,Description Missing,28,01/03/2023,239900,468,N,227000,Townhouse,1.0,East Isabellaport,1.5,2,2023-01-31,33.0,2023.0,01-2023,1
940,6/30/2022,Description Missing,36,02/07/2022,124900,1363,N,135000,Garden Apartment,2.0,Davidburgh,1.0,1,2022-03-16,24.0,2022.0,03-2022,3
941,12/26/2023,Description Missing,28,5/25/2023,285000,9501,N,285000,Townhouse,1.0,East Isabellaport,1.5,3,2023-06-22,33.0,2023.0,06-2023,6
942,6/30/2023,Description Missing,40,09/08/2022,244990,8266,N,235000,Townhouse,2.0,East Isabellaport,1.5,3,2022-10-18,33.0,2022.0,10-2022,10
943,6/15/2023,Mint,6,12/15/2022,289999,7496,N,295000,Townhouse,1.0,Bradfordberg,1.0,2,2022-12-30,33.0,2022.0,12-2022,12
944,08/06/2023,Description Missing,10,03/06/2023,309000,7089,N,320000,Townhouse,1.0,Bradfordberg,1.0,2,2023-03-24,33.0,2023.0,03-2023,3
945,12/31/2023,Mint,8,06/02/2023,315000,980,N,350000,Townhouse,1.0,Bradfordberg,1.0,2,2023-06-22,33.0,2023.0,06-2023,6
946,3/31/2022,Mint,13,9/22/2021,185000,7222,N,185500,Other,1.0,New Sophia,1.0,1,2021-10-05,54.0,2021.0,10-2021,10
947,11/30/2022,Mint,50,5/23/2022,200000,3608,N,215000,Other,1.0,New Sophia,1.0,1,2022-07-12,54.0,2022.0,07-2022,7
948,04/01/2022,Mint,23,07/01/2021,235000,7761,N,258000,Other,1.0,New Sophia,1.0,2,2021-07-28,54.0,2021.0,07-2021,7
949,8/22/2023,Good,28,8/23/2022,279000,2953,N,265000,Townhouse,1.0,East Isabellaport,1.5,3,2022-09-20,33.0,2022.0,09-2022,9
950,12/13/2022,Good,98,6/21/2022,239000,498,N,200000,Townhouse,1.0,East Isabellaport,1.5,2,2022-09-27,33.0,2022.0,09-2022,9
951,4/14/2023,Good,34,4/22/2022,239000,5763,N,220000,Townhouse,1.0,East Isabellaport,1.5,2,2022-05-26,33.0,2022.0,05-2022,5
952,02/01/2022,Description Missing,65,9/20/2021,249000,33,N,242000,Townhouse,1.0,East Isabellaport,1.5,3,2021-11-24,33.0,2021.0,11-2021,11
953,9/15/2022,Good,25,9/23/2021,194999,9710,N,195000,Townhouse,2.0,East Isabellaport,1.5,2,2021-10-18,33.0,2021.0,10-2021,10
954,05/01/2023,Description Missing,20,11/07/2022,129999,7393,N,135000,Garden Apartment,2.0,Davidburgh,1.0,1,2022-11-28,24.0,2022.0,11-2022,11
955,7/20/2022,Excellent,7,4/21/2022,265000,1172,N,265000,Garden Apartment,1.0,Port Regina,1.0,2,2022-05-12,10.0,2022.0,05-2022,5
956,8/12/2021,Excellent,8,5/13/2021,210000,2589,N,207000,Garden Apartment,2.0,Port Regina,1.0,1,2021-06-01,10.0,2021.0,06-2021,6
957,12/31/2023,Excellent,14,2/10/2023,339000,253,N,359000,Townhouse,1.0,Bradfordberg,1.0,2,2023-02-24,33.0,2023.0,02-2023,2

# Pre-Processing

In [6]:
# fix the olumn names
condo.rename(columns=lambda x: x.replace(' ', '_'), inplace=True)

In [7]:
# purge duplicate ML#s
condo = condo.drop_duplicates(subset=['ML#'], keep='first')

In [8]:
# prompt: drop any rows where ther sold price is null

condo.dropna(subset=['Sold_Price'], inplace=True)

<ipython-input-8-618774c0c9de>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  condo.dropna(subset=['Sold_Price'], inplace=True)

In [9]:
# select columns

condo = condo[['ML#', 'Style','Development','Sold_Price',
                   'Bath','Bedrooms','Appearance',
                'Unit_on_Floor_#','Contract_Date','Days_On_Market',
                'Listing_Price','Exp_Date']]

In [10]:
# Ensure the column is treated as a string or categorical
condo['Unit_on_Floor_#'] = condo['Unit_on_Floor_#'].astype(str)

In [11]:
value_counts = condo['Unit_on_Floor_#'].value_counts(dropna=False)
value_counts

1      558
2      161
1.0     88
2.0     52
nan     12
0       12
3        8
4        6
11       2
13       1
B        1
231      1
71       1
93       1
33       1
0.0      1
40       1
Name: Unit_on_Floor_#, dtype: int64

In [12]:
# Agents are more likely to omit Floor Number if it is ont he ground
# than if ioon the 2nd
#
condo['Unit_on_Floor_#'] = condo['Unit_on_Floor_#'].replace(0, 1)

In [13]:
condo['Unit_on_Floor_#'] = condo['Unit_on_Floor_#'].fillna(1)

In [14]:
# Drop rows where 'Unit_on_Floor_#' contains 'B'
#condo = condo[condo['Unit_on_Floor_#'] != 'B']
condo = condo[~condo['Unit_on_Floor_#'].str.contains('\.')]

In [15]:
# #Similarly Agents are more likely to omit if it
# # is a 1 bedroom than 2.
# # none are studios

# # Then, convert the column to integers
# condo['Unit_on_Floor_#'] = condo['Unit_on_Floor_#'].astype(int)

# # Convert 'Bedrooms' to a categorical data type
# condo['Unit_on_Floor_#'] = condo['Unit_on_Floor_#'].astype('category')

In [16]:
condo.shape

(766, 12)

# Developments

In [17]:
condo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 766 entries, 0 to 910
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ML#              766 non-null    int64
 1   Style            764 non-null    object
 2   Development      766 non-null    object
 3   Sold_Price       766 non-null    object
 4   Bath             766 non-null    float64
 5   Bedrooms         766 non-null    int64
 6   Appearance       766 non-null    object
 7   Unit_on_Floor_#  766 non-null    object
 8   Contract_Date    766 non-null    object
 9   Days_On_Market   766 non-null    int64
 10  Listing_Price    766 non-null    int64
 11  Exp_Date         763 non-null    object
dtypes: float64(1), int64(4), object(7)
memory usage: 77.8+ KB

In [18]:
dev_counts = condo['Development'].value_counts(dropna=False)
dev_counts

Port Barbaraport     79
East Melissa         70
New Heidimouth       63
Jodifort             49
Port Michael         49
New Bonnie           46
East Michaelstad     44
North Mikefort       32
Sarabury             30
East Kennethfurt     28
Allisonville         25
Stewartport          23
East Christopher     20
Angelaport           17
New Ashley           17
Cindyborough         16
Hernandezstad        15
East Charlesmouth    14
West Joanna          14
Lake Aaron           13
Griffinton           12
Port Amy             12
East John            12
Walkershire          12
Lisaberg             11
New Moniqueview      11
Port David           10
Williamsland          9
Bradfordberg          6
Port Stacyfort        4
Davidburgh            2
New Sophia            1
Name: Development, dtype: int64

In [19]:
# Developments = sorted(condo['Development'].unique())
# Developments

If some of the Developments were redundant becasue of typos we would consolidate them like this

In [20]:
# condo['Development'] = condo['Development'].replace(['Green Village',
#  'Greenwood',
#  'Greenwood Realty',
#  'Greenwood Vill',
#  'Greenwood Villag',
#  'Greenwood Village',
#  'Greenwood Village 55+',
#  'Greenwood Villagge',
#  'Greenwood Villiage'], 'Greenwood Village')

## Here all of the versions would become 'Greenwood Village'

# We will look at just the one development

In [21]:
condo = condo[condo['Development'] == 'Port Barbaraport']
condo

,ML#,Style,Development,Sold_Price,Bath,Bedrooms,Appearance,Unit_on_Floor_#,Contract_Date,Days_On_Market,Listing_Price,Exp_Date
7,7843,Townhouse,Port Barbaraport,242000,1.5,2,Description Missing,1,2022-07-29,3,229000,10/20/2022
8,9250,Other,Port Barbaraport,275000,1.0,1,Description Missing,1,2022-07-25,5,249000,7/20/2023
17,7972,Other,Port Barbaraport,265000,2.0,2,Description Missing,2,2022-08-30,19,315000,8/11/2023
20,7464,Other,Port Barbaraport,300000,1.5,2,Mint,1,2022-09-30,36,319000,2/25/2023
31,4537,Other,Port Barbaraport,262000,1.5,1,Excellent,1,2022-10-06,5,249000,10/31/2023
33,5555,Other,Port Barbaraport,285000,1.5,3,Description Missing,1,2022-10-06,2,285000,4/15/2023
44,8293,Other,Port Barbaraport,288000,1.0,1,Mint,1,2023-02-24,91,294990,5/25/2023
57,3139,Other,Port Barbaraport,295000,2.0,2,Description Missing,2,2023-03-03,59,315000,1/03/2024
64,453,Garden Apartment,Port Barbaraport,300000,1.0,2,Description Missing,2,2023-03-23,12,274999,9/10/2023
71,8326,Other,Port Barbaraport,292000,1.0,2,Excellent,1,2023-05-02,12,274900,12/31/2023
328,1267,Other,Port Barbaraport,300000,2.0,2,Good,1,2022-02-17,20,300000,7/28/2022
331,5059,Other,Port Barbaraport,285000,1.0,2,Mint,1,2022-03-02,28,295500,2/02/2023
332,632,Townhouse,Port Barbaraport,365000,2.5,3,Description Missing,2,2022-03-07,15,359000,7/17/2022
334,6762,Other,Port Barbaraport,310000,1.0,2,Mint,1,2022-04-11,57,320000,8/30/2022
337,7400,Other,Port Barbaraport,330000,2.0,2,Description Missing,2,2022-03-16,1,325000,9/01/2022
338,708,Other,Port Barbaraport,330000,2.0,2,Mint,1,2022-04-01,33,335000,8/30/2022
340,9486,Other,Port Barbaraport,350000,1.5,2,Description Missing,1,2022-03-18,10,355000,8/31/2022
342,9507,Townhouse,Port Barbaraport,355000,1.5,3,Description Missing,1,2022-03-19,10,365000,2/18/2023
343,3966,Other,Port Barbaraport,360000,2.0,2,Description Missing,1,2022-03-28,19,340000,9/09/2022
345,1135,Other,Port Barbaraport,320000,2.0,2,Description Missing,1,2022-03-21,11,299000,8/31/2022
347,3078,Townhouse,Port Barbaraport,291000,1.5,3,Description Missing,1,2022-05-19,72,320000,8/31/2022
348,8173,Other,Port Barbaraport,320000,1.0,2,Description Missing,1,2022-04-01,7,309000,9/15/2022
349,5722,Garden Apartment,Port Barbaraport,370000,1.5,2,Mint,1,2022-03-23,9,325000,9/14/2022
350,4989,Townhouse,Port Barbaraport,371000,2.0,3,Excellent,1,2022-04-27,43,369000,9/15/2022
352,3977,Other,Port Barbaraport,340000,2.0,2,Excellent,1,2022-04-07,10,309999,9/23/2022
359,6595,Townhouse,Port Barbaraport,369990,2.5,3,Excellent,1,2022-04-25,22,369990,4/01/2023
362,9384,Townhouse,Port Barbaraport,420000,2.5,3,Excellent,1,2022-08-26,144,400000,12/31/2022
363,4124,Garden Apartment,Port Barbaraport,220000,2.0,2,Description Missing,1,2022-04-26,21,175000,9/04/2022
366,7011,Townhouse,Port Barbaraport,276000,1.5,2,Good,1,2022-04-29,18,254900,7/09/2022
369,1375,Other,Port Barbaraport,325000,2.0,2,Mint,2,2022-04-25,11,325000,4/14/2023
370,647,Townhouse,Port Barbaraport,375000,2.5,3,Description Missing,1,2022-05-01,15,385000,4/16/2023
374,4137,Townhouse,Port Barbaraport,360000,1.5,2,Mint,0,2022-07-21,87,349900,11/25/2022
378,9388,Townhouse,Port Barbaraport,410000,2.5,3,Mint,0,2022-05-16,12,399990,10/29/2022
379,1794,Other,Port Barbaraport,345000,2.0,2,Excellent,1,2022-05-23,21,329999,8/02/2022
383,8971,Townhouse,Port Barbaraport,365000,2.5,3,Excellent,1,2022-08-29,111,340000,10/10/2022
385,3126,Other,Port Barbaraport,355000,2.5,3,Description Missing,2,2022-10-03,145,369990,11/30/2022
387,1350,Townhouse,Port Barbaraport,330000,1.5,2,Description Missing,1,2022-05-26,10,314000,10/31/2022
390,6070,Townhouse,Port Barbaraport,390000,2.5,3,Mint,1,2022-06-08,12,389900,11/21/2022
391,8884,Townhouse,Port Barbaraport,325000,1.5,2,Description Missing,1,2022-09-20,119,349900,9/30/2022
402,4487,Other,Port Barbaraport,316000,1.5,2,Description Missing,1,2022-06-09,2,310000,6/07/2023
403,5114,Other,Port Barbaraport,380000,2.5,3,Description Missing,1,2022-08-22,74,379000,12/31/2022
407,4812,Other,Port Barbaraport,258000,1.0,2,Description Missing,2,2022-07-12,26,275000,12/16/2022
409,4566,Townhouse,Port Barbaraport,277000,1.0,1,Mint,1,2022-07-11,24,269000,9/17/2022
410,9452,Other,Port Barbaraport,360000,1.5,3,Description Missing,1,2022-08-03,47,349000,12/17/2022
412,2537,Other,Port Barbaraport,382500,2.0,2,Description Missing,1,2022-07-06,15,395000,6/21/2023
414,1173,Other,Port Barbaraport,280000,1.5,1,Excellent,1,2022-07-11,12,269990,12/31/2022
415,8465,Other,Port Barbaraport,375000,2.0,2,Description Missing,1,2022-07-27,28,388000,6/27/2023
416,6890,Townhouse,Port Barbaraport,329000,1.5,2,Description Missing,1,2022-08-16,38,329000,7/08/2023
419,322,Other,Port Barbaraport,380000,2.0,2,Description Missing,1,2022-08-02,18,389000,7/15/2023
420,4677,Other,Port Barbaraport,325000,1.5,2,Mint,1,2022-08-01,16,325000,7/16/2023
421,2665,Townhouse,Port Barbaraport,360000,2.0,2,Mint,2,2022-08-30,33,349900,1/31/2023
423,1109,Other,Port Barbaraport,350000,1.0,2,Mint,1,2022-08-23,21,359000,2/02/2023
425,2659,Other,Port Barbaraport,370000,2.0,2,Description Missing,1,2022-09-07,29,359000,2/09/2023
429,6284,Other,Port Barbaraport,389000,2.5,3,Description Missing,2,2023-01-19,145,390000,8/27/2023
430,2117,Other,Port Barbaraport,395000,2.5,3,Mint,1,2022-10-20,38,389000,4/30/2023
432,3389,Other,Port Barbaraport,370000,1.5,2,Description Missing,1,2022-10-04,18,379000,10/12/2022
434,882,Other,Port Barbaraport,317500,2.0,2,Excellent,1,2022-10-24,32,334900,3/21/2023
436,9094,Townhouse,Port Barbaraport,395000,2.5,3,Excellent,1,2022-12-12,56,414999,6/17/2023
437,3427,Other,Port Barbaraport,340000,2.0,2,Description Missing,4,2022-11-13,10,349000,6/02/2023
438,2328,Townhouse,Port Barbaraport,305000,1.0,2,Mint,2,2022-11-16,12,299999,1/06/2023
439,2245,Other,Port Barbaraport,360000,1.5,2,Description Missing,1,2023-02-01,86,369000,12/04/2022
440,4532,Townhouse,Port Barbaraport,347000,1.5,2,Description Missing,1,2022-11-28,19,349000,12/01/2022
441,6456,Other,Port Barbaraport,312000,2.0,2,Description Missing,2,2022-12-12,76,334999,9/27/2023
443,7887,Townhouse,Port Barbaraport,360000,1.5,2,Description Missing,1,2023-01-03,32,369000,1/10/2023
444,6364,Townhouse,Port Barbaraport,345000,2.0,2,Mint,1,2023-03-09,97,360000,6/01/2023
445,3968,Other,Port Barbaraport,377500,2.0,2,Mint,1,2023-01-04,29,385000,6/01/2023
447,2482,Townhouse,Port Barbaraport,400000,1.5,3,Mint,1,2023-02-14,64,389900,5/31/2023
449,29,Other,Port Barbaraport,344000,2.0,2,Description Missing,1,2023-01-20,35,349990,12/16/2023
450,3896,Other,Port Barbaraport,350000,2.0,2,Mint,1,2023-02-21,56,349989,6/16/2023
452,2071,Townhouse,Port Barbaraport,389000,1.5,3,Description Missing,1,2023-01-17,15,389000,2/15/2023
454,5011,Townhouse,Port Barbaraport,395000,1.5,3,Description Missing,1,2023-01-31,14,399000,3/01/2023
458,5584,Townhouse,Port Barbaraport,355000,1.5,2,Description Missing,1,2023-03-01,21,350000,8/08/2023
460,3597,Other,Port Barbaraport,349000,2.0,2,Mint,1,2023-03-17,31,349000,2/13/2024
462,6393,Garden Apartment,Port Barbaraport,327000,2.0,2,Excellent,1,2023-04-03,24,329000,8/31/2023
464,77,Other,Port Barbaraport,367500,1.5,2,Mint,1,2023-03-31,49,349999,8/09/2023
468,6647,Garden Apartment,Port Barbaraport,370000,2.0,2,Mint,2,2023-04-07,3,339000,10/31/2023
472,9253,Other,Port Barbaraport,375000,1.5,3,Description Missing,2,2023-05-08,4,349999,4/10/2024
474,4863,Other,Port Barbaraport,360000,1.0,2,Mint,1,2023-05-10,20,354999,10/20/2023
478,4266,Other,Port Barbaraport,336000,1.0,2,Description Missing,2,2023-07-10,15,309990,2/29/2024

In [22]:
condo.shape

(79, 12)

# Appearance

In [23]:
# get list of all Appearance descriptions
Appearance_terms = sorted(condo['Appearance'].unique())
Appearance_terms

['Description Missing', 'Excellent', 'Good', 'Mint']

## Again if there were lots of Appearance types we would consolidate them as we did with the Devlopments

In [24]:
# condo['Appearance'] = condo['Appearance'].replace(['6M Mint', 'Exc/Mint', 'MINT',
#  'MINT +',
#  'MINT ++',
#  'MINT!',
#  'MINT++',
#  'Mint',
#  'Mint *',
#  'Mint +',
#  'Mint ++',
#  'Mint +++',
#  'Mint ++++',
#  'Mint+',
#  'Mint++',
#  'Mint+++','DIAMOND',
#  'DIAMOND++',
#  'DIAMOND+++',
#  'DIamond',
#  'Diam',
#  'Diamnond++',
#  'Diamod',
#  'Diamond',
#  'Diamond +',
#  'Diamond ++',
#  'Diamond+',
#  'Diamond++',
#  'Diamond+++', 'diamond',
#  'diamond +',
#  'diamond ++',
#  'diamond!!',
#  'diamond+','mINT',
#  'mint',
#  'mint +',
#  'mint+',
#  'mint++',
#  'mint+++',
#  'mlnt++','Perfect',
#  'Prestine',
#  'Pristene',
#  'Pristine',
#  'Superb',
#  'munt ++','pristene',
#  'pristine','perfect','Beautiful', 'Gorgeous','New',
#  'See Pics!','Like New','Amazing',
#  'Diamond Aa',
#  'New /Mint'], "Mint")

# Bedrooms

In [25]:
condo['Bedrooms'].fillna(1, inplace=True)

# Then, convert the column to integers
condo['Bedrooms'] = condo['Bedrooms'].astype(int)

# Convert 'Bedrooms' to a categorical data type
condo['Bedrooms'] = condo['Bedrooms'].astype('category')

# Every unit must have at least 1 Full Bath

In [26]:
condo['Bath'].fillna(1, inplace=True)

# Dates

Here we mutate teh date into something more usefull

In [27]:
condo['Contract_Date'] = pd.to_datetime(condo['Contract_Date'])
condo['Year'] = condo['Contract_Date'].dt.year

In [28]:
condo['Month_Year'] = condo['Contract_Date'].dt.strftime('%m-%Y')

In [29]:
condo['Month'] = condo['Contract_Date'].dt.strftime('%m')

In [30]:
condo['Month_Year'] = pd.to_datetime(condo['Month_Year'])

# Days On Mkt

In [31]:
condo['Days_On_Market'] = condo['Days_On_Market'].astype(int)

In [32]:
condo.shape

(79, 15)

In [41]:
condo['Sold_Price'] = pd.to_numeric(condo['Sold_Price'])

# Plot

In [33]:
condo.shape

(79, 15)

# Drop Down Menus

In [43]:
#6

import plotly.graph_objects as go
import plotly.express as px
import pandas as pd  # Make sure to import pandas

# Convert 'Sold_Price' to numeric
condo['Sold_Price'] = pd.to_numeric(condo['Sold_Price'])

# Create a color mapping dictionary
color_mapping = {
    'Mint': 'green',
    'Description Missing': 'red',
    'Excellent': 'blue',
    'Good': 'orange'
}

# Create the scatter plot first
fig = px.scatter(data_frame=condo, x='Month_Year', y='Sold_Price', color='Appearance',
                 title='Bedrooms and Bath Count v Sold Price',
                 labels={'Development': 'Development', 'Sold_Price': 'Sold Price', 'Town': 'Town'},
                 hover_data=['Development', 'ML#'])

# Remove the default legend
fig.update_traces(showlegend=False)

# Add legend entries as separate scatter traces
for appearance, color in color_mapping.items():
    fig.add_trace(go.Scatter(x=[None], y=[None], mode='markers',
                             marker=dict(size=10, color=color), name=appearance))

# Update the layout for the desired width and height
fig.update_layout(width=1000, height=600)

# Add dropdown menus for Bedrooms and Baths
fig.update_layout(updatemenus=[
    dict(type='dropdown',
         x=1.15,
         y=0.7,
         buttons=[
             dict(label='All Bedrooms',
                  method='update',
                  args=[{'visible': [True] * len(condo)},
                        {'title': 'All Bedrooms: Sold Price v Condition'}]),
             dict(label='2 Bedrooms',
                  method='update',
                  args=[{'visible': [bedrooms == 2 for bedrooms in condo['Bedrooms']]},
                        {'title': 'Two Bedrooms: Sold Price v Condition'}]),
             dict(label='1 Bedroom',
                  method='update',
                  args=[{'visible': [bedrooms == 1 for bedrooms in condo['Bedrooms']]},
                        {'title': 'One Bedroom: Sold Price v Condition'}]),
         ]),
    dict(type='dropdown',
         x=1.15,
         y=0.6,
         buttons=[
             dict(label='All Baths',
                  method='update',
                  args=[{'visible': [True] * len(condo)},
                        {'title': 'All Baths: Sold Price v Condition'}]),
             dict(label='1 Bath',
                  method='update',
                  args=[{'visible': [bath == 1 for bath in condo['Bath']]},
                        {'title': 'One Bath: Sold Price v Condition'}]),
             dict(label='2 Baths',
                  method='update',
                  args=[{'visible': [bath == 2 for bath in condo['Bath']]},
                        {'title': 'Two Baths: Sold Price v Condition'}]),
         ]),
])

# Update the x-axis tick format to show both month and year with monthly tick marks
fig.update_layout(xaxis=dict(tickangle=45, tickformat='%b %Y', dtick='M3'))

# Set custom y-axis tick marks starting at 200,000 with intervals of 50,000
fig.update_layout(yaxis=dict(tickmode='linear', tick0=200000, dtick=25000))

# Change the background color
fig.update_layout(plot_bgcolor='lightblue')

# Show the plot
fig.show()